/**
 * Sessions Service — Phase 3 + Phase 7
 *
 * Phase 7 change: steps 5 & 6 (AI memory + weak areas) now go
 * through the queue dispatcher instead of inline fire-and-forget.
 *
 * With Redis:    → queued, retried up to 3× on failure
 * Without Redis: → inline fire-and-forget (identical to before)
 *
 * Everything else is unchanged.
 */

import { db }                      from '../../core/database/client';
import { AppError }                from '../../core/utils/errors';
import { logger }                  from '../../infra/logger';
import { computeScoreBreakdown, FeedbackForScoring } from '../ai/scoring';
import {
  dispatchPersistMistakes,
  dispatchRecomputeWeakAreas,
} from '../../infra/queue/dispatcher';
import type { FeedbackItem } from '../ai/ai.memory';
import { maybeRewardReferrer } from '../growth/referral.service';
import { incrementAIUsage }   from '../user/user.service';

const log = logger.child({ module: 'sessions' });

// ── Types ─────────────────────────────────────────────────────────

export interface SaveSessionInput {
  userId:            string;
  client_session_id: string;  // ← stable UUID generated by client at session start;
                               //   used as idempotency key so POST /sessions retries
                               //   never create duplicate session or feedback rows.
  profession:        string;
  mode:              string;
  difficulty:        string;
  interview_type:    string;
  personality:       string;
  score:             number;
  exchanges:         number;
  duration_secs:     number;
  hindi_mode:        boolean;
  feedbacks?:        FeedbackInput[];
}

export interface FeedbackInput {
  q?:              string;
  question?:       string;
  answer?:         string;
  score?:          number;
  english_errors?: string[];
  corrections?:    unknown[];
  tip?:            string;
  tips?:           string;
  structure?:      Record<string, unknown>;
  model_answer?:   Record<string, unknown>;
}

export interface SaveSessionResult {
  session_id:      string;
  streak:          number;
  sessions:        number;
  best_score:      number;
  job_ready_score: number;
  score_breakdown: {
    clarity:   number;
    structure: number;
    relevance: number;
    grammar:   number;
  };
  // ── Monetization signals ──────────────────────────────────────────
  // Computed from session outcome + user stats so the frontend can fire
  // the right contextual upsell at exactly the right moment.
  // Only set when a trigger condition is met — absent otherwise.
  upsell_trigger?: {
    reason:  'post_session'       // every session end for free users → upgrade push
           | 'high_score'         // score ≥ 7.5 → "unlock full analytics"
           | 'streak_milestone';  // streak 3 / 7 / 14 → momentum upsell
    score?:  number;              // present when reason = high_score
    streak?: number;              // present when reason = streak_milestone
  };
}

// ── Save session ──────────────────────────────────────────────────

// ── In-flight guard — prevents double-submit on retry / laggy connections ──
// Maps client_session_id → { promise, startedAt }.
//
// Safety guarantees:
//   1. Deduplication: a second call with the same client_session_id while the
//      first is still running returns the existing promise — no parallel writes.
//   2. Stuck-promise eviction: if a server restart or uncaught rejection leaves
//      an entry in the map forever (promise.finally never ran), a new call after
//      INFLIGHT_TTL_MS will evict the stale entry and start fresh.  Without this,
//      a single crashed save permanently locks that client_session_id for the
//      lifetime of the process.
//
// FIX H5: Previously keyed on userId — meaning two genuinely different sessions
// submitted rapidly by the same user would collide: the second call would return
// the first session's result entirely. The correct idempotency key is
// client_session_id, which uniquely identifies one interview session.

const INFLIGHT_TTL_MS = 30_000; // evict stale entries after 30 s

interface InFlightEntry {
  promise:   Promise<SaveSessionResult>;
  startedAt: number;
}

const _inFlight = new Map<string, InFlightEntry>();

export async function saveSession(input: SaveSessionInput): Promise<SaveSessionResult> {
  const key = input.client_session_id;

  const existing = _inFlight.get(key);
  if (existing) {
    const age = Date.now() - existing.startedAt;
    if (age < INFLIGHT_TTL_MS) {
      log.warn('saveSession called while previous save still in flight — returning existing promise', {
        userId: input.userId, client_session_id: key, age_ms: age,
      });
      return existing.promise;
    }
    // Stale entry (process restart / unhandled rejection left it orphaned) — evict and retry.
    log.warn('saveSession: evicting stale in-flight entry', {
      userId: input.userId, client_session_id: key, age_ms: age,
    });
    _inFlight.delete(key);
  }

  const promise = _saveSession(input);
  _inFlight.set(key, { promise, startedAt: Date.now() });
  promise.finally(() => _inFlight.delete(key));
  return promise;
}

async function _saveSession(input: SaveSessionInput): Promise<SaveSessionResult> {
  const {
    userId, client_session_id, profession, mode, difficulty,
    interview_type, personality, score,
    exchanges, duration_secs, hindi_mode, feedbacks,
  } = input;

  // 1. Compute score breakdown
  const feedbacksForScoring: FeedbackForScoring[] = (feedbacks || []).map(f => ({
    score:          f.score,
    english_errors: f.english_errors,
    corrections:    f.corrections as unknown[],
    structure:      f.structure,
    tips:           f.tip || f.tips,
    answer:         f.answer,
  }));

  const breakdown = computeScoreBreakdown(feedbacksForScoring);

  // 2. Save session record — idempotent via client_session_id unique constraint.
  //    A client retry with the same client_session_id returns the existing row
  //    rather than inserting a duplicate.  See MIGRATION.sql for the constraint.
  const session = await db.createSession({
    client_session_id: client_session_id,
    user_id:           userId,
    profession:        profession     || 'General',
    mode:              mode           || 'classic',
    difficulty:        difficulty     || 'beginner',
    interview_type:    interview_type || 'mixed',
    personality:       personality    || 'friendly',
    score:             score          || 0,
    exchanges:         exchanges      || 0,
    duration_secs:     duration_secs  || 0,
    hindi_mode:        hindi_mode     || false,
    clarity_score:     breakdown.clarity,
    structure_score:   breakdown.structure,
    relevance_score:   breakdown.relevance,
    grammar_score:     breakdown.grammar,
    job_ready_score:   breakdown.jobReady,
  });

  if (!session?.id) throw new AppError(500, 'session_creation_failed', 'Failed to create session record');

  // 3. Save feedback records (non-fatal on individual failures).
  //    Each row is keyed by (session_id, question_index) so that a client
  //    retry of the same POST /sessions doesn't produce duplicate feedback rows.
  //    The DB constraint is:  UNIQUE (session_id, question_index)
  //    and the insert uses ON CONFLICT DO NOTHING via the prefer header.
  if (feedbacks && feedbacks.length > 0) {
    await Promise.allSettled(
      feedbacks.map((f, idx) =>
        db.createFeedback({
          session_id:     session.id!,
          question_index: idx,
          question:       f.q || f.question || '',
          answer:         f.answer          || '',
          score:          f.score           || 0,
          corrections:    JSON.stringify(f.english_errors || f.corrections || []),
          tips:           f.tip || f.tips   || '',
          structure:      JSON.stringify(f.structure    || {}),
          model_answer:   JSON.stringify(f.model_answer || {}),
        })
      )
    );
  }

  // 4. Atomically increment stats — ALL arithmetic lives in Postgres.
  //    No JS read → no race condition.  The SQL function holds a row-level
  //    lock (FOR UPDATE) for the duration so concurrent sessions serialize
  //    at the DB layer, not the application layer.
  const updatedStats = await db.incrementStats(
    userId,
    score          || 0,
    breakdown.jobReady,
    score          || 0,   // total_score delta = this session's score
  );

  const newSessions = updatedStats.sessions;
  const newBest     = updatedStats.best_score;
  const newStreak   = updatedStats.streak;

  // 5. Increment AI usage quota — once per completed session, not per message.
  //    Non-fatal: a failed counter must never block the session save result.
  incrementAIUsage(userId).catch(err =>
    log.warn('incrementAIUsage failed (non-fatal)', { userId, error: (err as Error).message })
  );

  // 6. Reward referrer if this is the user's first session (non-fatal)
  if (newSessions === 1) {
    maybeRewardReferrer(userId).catch(err =>
      log.warn('maybeRewardReferrer failed (non-fatal)', { error: err })
    );
  }

  // 7. Score history for graph (non-fatal)
  db.addScoreHistory({
    user_id:         userId,
    session_id:      session.id,
    score:           score || 0,
    job_ready_score: breakdown.jobReady,
    topic:           interview_type || profession,
  }).catch(err => log.warn('Score history insert failed (non-fatal)', { error: err }));

  // ── Phase 7: background jobs go through the queue dispatcher ────
  // With Redis    → queued with 3× retry + exponential backoff
  // Without Redis → inline fire-and-forget (dev / degraded mode)

  // 8. AI memory — persist recurring mistakes from this session
  if (feedbacks && feedbacks.length > 0) {
    dispatchPersistMistakes(
      userId,
      interview_type || profession,
      feedbacks as FeedbackItem[]
    ).catch(() => {/* dispatcher logs internally */});
  }

  // 9. Weak areas — recompute topic scores for the dashboard
  dispatchRecomputeWeakAreas(userId)
    .catch(() => {/* dispatcher logs internally */});

  log.info('Session saved', {
    userId,
    sessionId:     session.id,
    jobReadyScore: breakdown.jobReady,
    streak:        newStreak,
  });

  // Mark session as completed — state machine transition scoring → completed.
  // WHERE status='scoring' in the SQL means duplicate calls are no-ops.
  await db.completeSession(session.id!);

  // ── Monetization trigger — computed once, passed to controller ────
  // Priority: streak_milestone > high_score > post_session (free fallback).
  // Only one trigger fires per session; the frontend shows one contextual
  // upsell, not a stack of them.
  const STREAK_MILESTONES = [3, 7, 14];
  const upsell_trigger: SaveSessionResult['upsell_trigger'] =
    STREAK_MILESTONES.includes(newStreak)
      ? { reason: 'streak_milestone', streak: newStreak }
      : (score || 0) >= 7.5
        ? { reason: 'high_score', score: score || 0 }
        : undefined;   // controller sets 'post_session' for free users if no other trigger

  return {
    session_id:      session.id,
    streak:          newStreak,
    sessions:        newSessions,
    best_score:      newBest,
    job_ready_score: breakdown.jobReady,
    score_breakdown: {
      clarity:   breakdown.clarity,
      structure: breakdown.structure,
      relevance: breakdown.relevance,
      grammar:   breakdown.grammar,
    },
    upsell_trigger,
  };
}

// ── List sessions (paginated) ─────────────────────────────────────

export async function listSessions(userId: string, page = 1, pageSize = 10) {
  const offset   = (page - 1) * pageSize;
  const sessions = await db.getUserSessions(userId, pageSize, offset);
  return {
    sessions,
    page,
    page_size: pageSize,
    has_more:  sessions.length === pageSize,
  };
}

// ── Get session detail with parsed feedback ───────────────────────

export async function getSessionDetail(sessionId: string, userId: string) {
  const session = await db.getSessionById(sessionId, userId);
  if (!session) return null;

  const feedbacks = await db.getSessionFeedback(sessionId);

  const parsed = feedbacks.map(f => ({
    ...f,
    corrections:  safeJsonParse(f.corrections, []),
    structure:    safeJsonParse(f.structure,    {}),
    model_answer: safeJsonParse(f.model_answer, {}),
  }));

  return { session, feedbacks: parsed };
}

// ── Score history for chart ───────────────────────────────────────

export async function getScoreHistory(userId: string, limit = 30) {
  const history = await db.getScoreHistory(userId, limit);
  return history.reverse(); // oldest first for charting
}

// ── Session lifecycle enforcement (Issue 7) ───────────────────────
//
// saveSession() takes a session from 'scoring' -> 'completed' via
// db.completeSession(). If the client disconnects or the process
// crashes before that final step runs, the row is left in 'scoring'
// indefinitely — nothing else in the app revisits it.
//
// expireStaleSessions() is the lifecycle enforcement layer: it sweeps
// for 'scoring' rows older than STALE_SESSION_MS and marks them
// 'abandoned', closing the state machine. Safe to call repeatedly
// (idempotent — only rows still 'scoring' are touched). Scheduled via
// scheduleSessionExpiry() in infra/queue/dispatcher.ts.

const STALE_SESSION_MS = 30 * 60 * 1000; // 30 minutes

export async function expireStaleSessions(): Promise<number> {
  const expired = await db.expireStaleSessions(STALE_SESSION_MS);
  if (expired.length > 0) {
    log.info('Expired stale sessions', {
      count: expired.length,
      session_ids: expired.map(s => s.id),
    });
  }
  return expired.length;
}

// ── Helpers ───────────────────────────────────────────────────────

function safeJsonParse<T>(val: unknown, fallback: T): T {
  try {
    return typeof val === 'string' ? JSON.parse(val) : (val as T) ?? fallback;
  } catch {
    return fallback;
  }
}
