/**
 * Sessions Service
 *
 * Handles creating, querying, and expiring interview sessions.
 * After a save, background jobs run via the queue dispatcher (with Redis)
 * or inline fire-and-forget (without Redis / local dev).
 */

import { db }                      from '../../core/database/client';
import { AppError }                from '../../core/utils/errors';
import { PlanType, SESSION_CAP_FREE } from '../../core/config/env';
import { logger }                  from '../../infra/logger';
import { computeScoreBreakdown, FeedbackForScoring } from '../ai/scoring';
import {
  dispatchPersistMistakes,
  dispatchRecomputeWeakAreas,
  dispatchGenerateInterviewerNotes,
  dispatchGenerateReadinessReport,
} from '../../infra/queue/dispatcher';
import type { FeedbackItem } from '../ai/ai.memory';
import { maybeRewardReferrer } from '../growth/referral.service';
import { incrementAIUsage }   from '../user/user.service';
import { maybeAwardStreakVoiceBonus } from '../voice/voice.ledger';

const log = logger.child({ module: 'sessions' });

// Types

export interface SaveSessionInput {
  userId:            string;
  client_session_id: string;  // ← stable UUID generated by client at session start;
                               // used as idempotency key so POST /sessions retries
                               // never create duplicate session or feedback rows.
  profession:        string;
  mode:              string;
  difficulty:        string;
  interview_type:    string;
  personality:       string;
  score:             number;
  exchanges:         number;
  duration_secs:     number;
  hindi_mode:        boolean;
  feedbacks?:        FeedbackInput[];
}

export interface FeedbackInput {
  q?:              string;
  question?:       string;
  answer?:         string;
  score?:          number;
  english_errors?: string[];
  corrections?:    unknown[];
  tip?:            string;
  tips?:           string;
  structure?:      Record<string, unknown>;
  model_answer?:   Record<string, unknown>;
}

export interface SaveSessionResult {
  session_id:      string;
  streak:          number;
  sessions:        number;
  best_score:      number;
  job_ready_score: number;
  score_breakdown: {
    clarity:   number;
    structure: number;
    relevance: number;
    grammar:   number;
  };
  // Monetization signals
  // Computed from session outcome + user stats so the frontend can fire
  // the right contextual upsell at exactly the right moment.
  // Only set when a trigger condition is met — absent otherwise.
  upsell_trigger?: {
    reason:  'post_session'       // every session end for free users → upgrade push
           | 'high_score'         // score ≥ 7.5 → "unlock full analytics"
           | 'streak_milestone';  // streak 3 / 7 / 14 → momentum upsell
    score?:  number;              // present when reason = high_score
    streak?: number;              // present when reason = streak_milestone
  };
}

// Save session

// In-flight guard — prevents double-submit on retry / laggy connections
// Maps client_session_id → { promise, startedAt }.
//
// Safety guarantees:
// 1. Deduplication: a second call with the same client_session_id while the
// first is still running returns the existing promise — no parallel writes.
// 2. Stuck-promise eviction: if a server restart or uncaught rejection leaves
// an entry in the map forever (promise.finally never ran), a new call after
// INFLIGHT_TTL_MS will evict the stale entry and start fresh.  Without this,
// a single crashed save permanently locks that client_session_id for the
// lifetime of the process.
//
// Previously keyed on userId — meaning two genuinely different sessions
// submitted rapidly by the same user would collide: the second call would return
// the first session's result entirely. The correct idempotency key is
// client_session_id, which uniquely identifies one interview session.

const INFLIGHT_TTL_MS = 30_000; // evict stale entries after 30 s

interface InFlightEntry {
  promise:   Promise<SaveSessionResult>;
  startedAt: number;
}

const _inFlight = new Map<string, InFlightEntry>();

// the TTL eviction above only fires when a *new* call arrives with
// the same client_session_id. If a save's `promise.finally(() => ...)`
// never runs (e.g. an uncaught rejection edge case bypasses `finally`, or
// the process is mid-shutdown), that entry stays in the map forever and is
// never revisited unless the exact same client_session_id happens to retry.
// On a long-running server processing thousands of distinct sessions, those
// orphaned entries accumulate indefinitely. This periodic sweep catches
// anything `finally` missed, independent of whether a new call ever arrives
// for that key.
setInterval(() => {
  const now = Date.now();
  for (const [key, entry] of _inFlight) {
    if (now - entry.startedAt > INFLIGHT_TTL_MS) {
      log.warn('saveSession: sweeping stale in-flight entry', {
        client_session_id: key, age_ms: now - entry.startedAt,
      });
      _inFlight.delete(key);
    }
  }
}, INFLIGHT_TTL_MS).unref();

export async function saveSession(input: SaveSessionInput): Promise<SaveSessionResult> {
  const key = input.client_session_id;

  const existing = _inFlight.get(key);
  if (existing) {
    const age = Date.now() - existing.startedAt;
    if (age < INFLIGHT_TTL_MS) {
      log.warn('saveSession called while previous save still in flight — returning existing promise', {
        userId: input.userId, client_session_id: key, age_ms: age,
      });
      return existing.promise;
    }
    // Stale entry (process restart / unhandled rejection left it orphaned) — evict and retry.
    log.warn('saveSession: evicting stale in-flight entry', {
      userId: input.userId, client_session_id: key, age_ms: age,
    });
    _inFlight.delete(key);
  }

  const promise = _saveSession(input);
  _inFlight.set(key, { promise, startedAt: Date.now() });
  promise.finally(() => _inFlight.delete(key));
  return promise;
}

async function _saveSession(input: SaveSessionInput): Promise<SaveSessionResult> {
  const {
    userId, client_session_id, profession, mode, difficulty,
    interview_type, personality, score,
    exchanges, duration_secs, hindi_mode, feedbacks,
  } = input;

  // ── P1-A: Monthly session cap for free-tier users ─────────────────────────
  //
  // Free users are limited to SESSION_CAP_FREE sessions per IST calendar month.
  // Paid plans (starter / pro / elite) are never gated here.
  //
  // Flow:
  //  1. Read the user's plan.
  //  2. If free, check if the IST month has rolled over since
  //     monthly_session_reset_at and lazily reset if so.
  //  3. Call increment_session_count(userId, cap) — a single atomic Postgres
  //     function that checks AND increments inside one row-locked UPDATE.
  //     Returns { new_count, blocked }.
  //  4. If blocked → 429 with a helpful reset-date message.
  //
  // Why atomic?  A two-step "read count → JS check → increment" has a TOCTOU
  // race: two concurrent POST /sessions from the same free user both read
  // count=2, both pass the JS guard, and both increment — yielding count=4.
  // Moving the check inside the Postgres UPDATE eliminates this because
  // Postgres serialises row-level locks on the usage row.
  //

  {
    const [dbUser, usage] = await Promise.all([
      db.getUserById(userId),
      db.getUsage(userId),
    ]);

    const plan = (dbUser?.plan as PlanType) ?? 'free';

    if (plan === 'free') {
      // Lazy monthly reset: if monthly_session_reset_at is in a previous IST
      // month, reset the counter before the cap check. Avoids a background cron.
      const resetAt = usage?.monthly_session_reset_at
        ? new Date(usage.monthly_session_reset_at)
        : null;

      const nowIST = new Date(new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
      const isNewMonth =
        !resetAt ||
        resetAt.getFullYear() < nowIST.getFullYear() ||
        (resetAt.getFullYear() === nowIST.getFullYear() &&
          resetAt.getMonth() < nowIST.getMonth());

      if (isNewMonth) {
        // Non-fatal: if reset fails the increment below still runs. Worst case:
        // the stale counter is slightly high for this request; the RPC's
        // atomic check prevents over-counting regardless.
        try {
          await db.resetUsage(userId);
          log.info('Monthly usage reset (lazy, new IST month)', { userId, plan });
        } catch (resetErr) {
          log.error('Monthly usage reset failed (non-fatal)', { userId, error: resetErr });
        }
      }

      // Single atomic RPC — check + increment in one row-locked Postgres UPDATE.
      // No JS pre-check needed; the RPC returns blocked=true if cap is reached.
      let capResult: { new_count: number; blocked: boolean };
      try {
        capResult = await db.incrementSessionCount(userId, SESSION_CAP_FREE);
      } catch (incErr) {
        // RPC failure: log and allow the session to save (under-count is
        // preferable to silently dropping a completed session).
        log.error('incrementSessionCount RPC failed (non-fatal, session will still save)', {
          userId, error: incErr,
        });
        capResult = { new_count: 1, blocked: false };
      }

      if (capResult.blocked) {
        const nextMonth = new Date(nowIST.getFullYear(), nowIST.getMonth() + 1, 1);
        throw new AppError(
          429,
          'session_limit_reached',
          `You've used all ${SESSION_CAP_FREE} free sessions for this month. ` +
          `Your sessions reset on ${nextMonth.toLocaleDateString('en-IN', { day: 'numeric', month: 'long' })}.`,
          {
            sessions_used:  capResult.new_count,
            session_limit:  SESSION_CAP_FREE,
            resets_at:      nextMonth.toISOString(),
          },
        );
      }
    }
    // Paid plans: no session cap — fall straight through.
  }
  // ── end P1-A ──────────────────────────────────────────────────────────────

  // FeedbackInput accepts notes under either `tip` (older clients) or `tips`
  // (newer clients). normalizedFeedbacks resolves the alias once so all
  // downstream consumers (AI memory, interviewer notes) get a consistent shape.
  const normalizedFeedbacks: FeedbackItem[] = (feedbacks || []).map(f => ({
    q:              f.q,
    question:       f.question,
    score:          f.score,
    english_errors: f.english_errors,
    corrections:    f.corrections,
    tips:           f.tip || f.tips || '',
    structure:      f.structure,
  }));

  // 1. Compute score breakdown
  const feedbacksForScoring: FeedbackForScoring[] = (feedbacks || []).map(f => ({
    score:          f.score,
    english_errors: f.english_errors,
    corrections:    f.corrections as unknown[],
    structure:      f.structure,
    tips:           f.tip || f.tips,
    answer:         f.answer,
  }));

  const breakdown = computeScoreBreakdown(feedbacksForScoring);

  // 2. Save session record — idempotent via client_session_id unique constraint.
  // A client retry with the same client_session_id returns the existing row
  // rather than inserting a duplicate.  See MIGRATION.sql for the constraint.
  const session = await db.createSession({
    client_session_id: client_session_id,
    user_id:           userId,
    profession:        profession     || 'General',
    mode:              mode           || 'classic',
    difficulty:        difficulty     || 'beginner',
    interview_type:    interview_type || 'mixed',
    personality:       personality    || 'friendly',
    score:             score          || 0,
    exchanges:         exchanges      || 0,
    duration_secs:     duration_secs  || 0,
    hindi_mode:        hindi_mode     || false,
    clarity_score:     breakdown.clarity,
    structure_score:   breakdown.structure,
    relevance_score:   breakdown.relevance,
    grammar_score:     breakdown.grammar,
    job_ready_score:   breakdown.jobReady,
  });

  if (!session?.id) throw new AppError(500, 'session_creation_failed', 'Failed to create session record');

  // 3. Save feedback records (non-fatal on individual failures).
  // Each row is keyed by (session_id, question_index) so that a client
  // retry of the same POST /sessions doesn't produce duplicate feedback rows.
  // The DB constraint is:  UNIQUE (session_id, question_index)
  // and the insert uses ON CONFLICT DO NOTHING via the prefer header.
  if (feedbacks && feedbacks.length > 0) {
    const results = await Promise.allSettled(
      feedbacks.map((f, idx) =>
        db.createFeedback({
          session_id:     session.id!,
          question_index: idx,
          question:       f.q || f.question || '',
          answer:         f.answer          || '',
          score:          f.score           || 0,
          corrections:    JSON.stringify(f.english_errors || f.corrections || []),
          tips:           f.tip || f.tips   || '',
          structure:      JSON.stringify(f.structure    || {}),
          model_answer:   JSON.stringify(f.model_answer || {}),
        })
      )
    );
    // Individual feedback rows staying non-fatal is intentional (one bad
    // row shouldn't fail the whole session save) — but now that
    // db.createFeedback() actually surfaces write failures instead of
    // swallowing them, log any rejections so a recurring DB problem is
    // visible instead of permanently invisible.
    results.forEach((r, idx) => {
      if (r.status === 'rejected') {
        log.error('Feedback row save failed (non-fatal)', {
          sessionId: session.id, questionIndex: idx, error: (r.reason as Error)?.message,
        });
      }
    });
  }

  // 4. Atomically increment stats — ALL arithmetic lives in Postgres.
  // No JS read → no race condition.  The SQL function holds a row-level
  // lock (FOR UPDATE) for the duration so concurrent sessions serialize
  // at the DB layer, not the application layer.
  //
  // Non-fatal: wrapped in try/catch so that a DB-level error (e.g. a
  // PostgREST PGRST203 function-overload ambiguity from a stale bigint
  // overload co-existing with the uuid version) doesn't propagate as an
  // unhandled rejection and crash the process.  Stats under-counting is
  // preferable to dropping the whole session result.  The error is still
  // logged as [err] so it shows up in Railway and Sentry.
  let updatedStats: { sessions: number; best_score: number; streak: number; avg_job_ready_score: number };
  try {
    updatedStats = await db.incrementStats(
      userId,
      score          || 0,
      breakdown.jobReady,
      score          || 0,   // total_score delta = this session's score
    );
  } catch (statsErr) {
    log.error('incrementStats failed (non-fatal) — stats not updated for this session', {
      userId, error: (statsErr as Error)?.message,
    });
    // Return zeroed-out stats so the session result can still be returned
    // to the client.  Streak-gated features (upsell triggers, readiness
    // report, voice bonus) will silently skip for this session only.
    updatedStats = { sessions: 0, best_score: 0, streak: 0, avg_job_ready_score: 0 };
  }

  const newSessions = updatedStats.sessions;
  const newBest     = updatedStats.best_score;
  const newStreak   = updatedStats.streak;

  // 5. Increment AI usage quota — once per completed session, not per message.
  // Non-fatal: a failed counter must never block the session save result.
  incrementAIUsage(userId).catch(err =>
    log.warn('incrementAIUsage failed (non-fatal)', { userId, error: (err as Error).message })
  );

  // 6. Reward referrer if this is the user's first session (non-fatal)
  if (newSessions === 1) {
    maybeRewardReferrer(userId).catch(err =>
      log.warn('maybeRewardReferrer failed (non-fatal)', { error: err })
    );
  }

  // 7. Score history for graph (non-fatal)
  db.addScoreHistory({
    user_id:         userId,
    session_id:      session.id,
    score:           score || 0,
    job_ready_score: breakdown.jobReady,
    topic:           interview_type || profession,
  }).catch(err => log.warn('Score history insert failed (non-fatal)', { error: err }));

  // background jobs go through the queue dispatcher
  // With Redis    → queued with 3× retry + exponential backoff
  // Without Redis → inline fire-and-forget (dev / degraded mode)

  // 8. AI memory — persist recurring mistakes from this session
  if (normalizedFeedbacks.length > 0) {
    dispatchPersistMistakes(
      userId,
      interview_type || profession,
      normalizedFeedbacks
    ).catch(() => {/* dispatcher logs internally */});
  }

  // 9. Weak areas — recompute topic scores for the dashboard
  dispatchRecomputeWeakAreas(userId)
    .catch(() => {/* dispatcher logs internally */});

  // 10. Interviewer's Notes — 2-3 sentence narrative summary, reusing the
  // same feedbacks already captured above. Same non-fatal, fire-and-
  // forget treatment as the other post-save background jobs.
  if (normalizedFeedbacks.length > 0) {
    dispatchGenerateInterviewerNotes(
      session.id!,
      profession || 'General',
      score || 0,
      normalizedFeedbacks
    ).catch(() => {/* dispatcher logs internally */});
  }

  log.info('Session saved', {
    userId,
    sessionId:     session.id,
    jobReadyScore: breakdown.jobReady,
    streak:        newStreak,
  });

  // Mark session as completed — state machine transition scoring → completed.
  // WHERE status='scoring' in the SQL means duplicate calls are no-ops.
  await db.completeSession(session.id!);

  // 11. Interview Readiness Report — every-5-sessions rollup on top of
  // Interviewer's Notes. Fired AFTER completeSession() so the new
  // session is already in 'completed' status when getRecentCompletedSessions
  // runs inside the job — firing before completeSession was a race: the
  // session could still be 'scoring' when the job queries, causing it to
  // read only 4 completed sessions and skip the report entirely.
  // Gated Starter+: skip the plan lookup + AI call entirely for Free users.
  // Non-fatal, same fire-and-forget treatment as the other post-save jobs.
  if (newSessions > 0 && newSessions % 5 === 0) {
    db.getUserById(userId)
      .then(dbUser => {
        const plan = dbUser?.plan ?? 'free';
        if (plan === 'starter' || plan === 'pro' || plan === 'elite') {
          return dispatchGenerateReadinessReport(userId, newSessions);
        }
      })
      .catch(err =>
        log.warn('Readiness report dispatch failed (non-fatal)', {
          userId, sessionCount: newSessions, error: (err as Error)?.message,
        })
      );
  }

  // Monetization trigger — computed once, passed to controller
  // Priority: streak_milestone > high_score > post_session (free fallback).
  // Only one trigger fires per session; the frontend shows one contextual
  // upsell, not a stack of them.
  const STREAK_MILESTONES = [3, 7, 14];
  const upsell_trigger: SaveSessionResult['upsell_trigger'] =
    STREAK_MILESTONES.includes(newStreak)
      ? { reason: 'streak_milestone', streak: newStreak }
      : (score || 0) >= 7.5
        ? { reason: 'high_score', score: score || 0 }
        : undefined;   // controller sets 'post_session' for free users if no other trigger

  // Award bonus voice minutes on streak milestones (7 / 14 / 21 / …).
  // Fired non-fatally — a failed top-up must never block the session result.
  // Uses its own milestone set (every 7 days, not just the upsell_trigger set)
  // so loyal Pro/Elite users accumulate voice bonus beyond the first 14 days.
  maybeAwardStreakVoiceBonus(userId, newStreak).catch(err =>
    log.warn('maybeAwardStreakVoiceBonus failed (non-fatal)', { userId, streak: newStreak, error: err })
  );

  return {
    session_id:      session.id,
    streak:          newStreak,
    sessions:        newSessions,
    best_score:      newBest,
    job_ready_score: breakdown.jobReady,
    score_breakdown: {
      clarity:   breakdown.clarity,
      structure: breakdown.structure,
      relevance: breakdown.relevance,
      grammar:   breakdown.grammar,
    },
    upsell_trigger,
  };
}

// List sessions (paginated)

export async function listSessions(userId: string, page = 1, pageSize = 10) {
  const offset   = (page - 1) * pageSize;
  const sessions = await db.getUserSessions(userId, pageSize, offset);
  return {
    sessions,
    page,
    page_size: pageSize,
    has_more:  sessions.length === pageSize,
  };
}

// Get session detail with parsed feedback

export async function getSessionDetail(sessionId: string, userId: string) {
  const session = await db.getSessionById(sessionId, userId);
  if (!session) return null;

  const feedbacks = await db.getSessionFeedback(sessionId);

  const parsed = feedbacks.map(f => ({
    ...f,
    corrections:  safeJsonParse(f.corrections, []),
    structure:    safeJsonParse(f.structure,    {}),
    model_answer: safeJsonParse(f.model_answer, {}),
  }));

  return { session, feedbacks: parsed };
}

// Score history for chart

export async function getScoreHistory(userId: string, limit = 30) {
  const history = await db.getScoreHistory(userId, limit);
  return history.reverse(); // oldest first for charting
}

// Session lifecycle enforcement
//
// saveSession() takes a session from 'scoring' -> 'completed' via
// db.completeSession(). If the client disconnects or the process
// crashes before that final step runs, the row is left in 'scoring'
// indefinitely — nothing else in the app revisits it.
//
// expireStaleSessions() is the lifecycle enforcement layer: it sweeps
// for 'scoring' rows older than STALE_SESSION_MS and marks them
// 'abandoned', closing the state machine. Safe to call repeatedly
// (idempotent — only rows still 'scoring' are touched). Scheduled via
// scheduleSessionExpiry() in infra/queue/dispatcher.ts.

const STALE_SESSION_MS = 30 * 60 * 1000; // 30 minutes

export async function expireStaleSessions(): Promise<number> {
  const expired = await db.expireStaleSessions(STALE_SESSION_MS);
  if (expired.length > 0) {
    log.info('Expired stale sessions', {
      count: expired.length,
      session_ids: expired.map(s => s.id),
    });
  }
  return expired.length;
}

// Helpers

function safeJsonParse<T>(val: unknown, fallback: T): T {
  try {
    return typeof val === 'string' ? JSON.parse(val) : (val as T) ?? fallback;
  } catch {
    return fallback;
  }
}