// Core domain types — mirror backend exactly

export type Plan = 'free' | 'starter' | 'pro' | 'elite';
export type SessionMode = 'classic' | 'chat';
export type Difficulty = 'beginner' | 'intermediate' | 'expert';
export type InterviewType = 'Technical' | 'Behavioral' | 'Mixed';
export type Persona = 'friendly' | 'strict' | 'encouraging';

export interface User {
  id: string;
  email: string;
  name: string;
  plan: Plan;
  email_verified: boolean;
  referral_code?: string;
  referral_bonus?: number;
  ai_calls?: number;
  /** null = unlimited (pro/elite); populated from usage.limit in /me response */
  ai_calls_limit?: number | null;
  /** null = unlimited; populated from usage.remaining in /me response */
  ai_calls_remaining?: number | null;
  onboarding_profession?: string | null;
  onboarding_goal?: string | null;
  onboarding_completed_at?: string | null;
  is_admin?: boolean;
  created_at?: string;
  // P3-A: set once user submits job-landed form; null until then.
  // Drives dashboard card visibility without unsafe casts.
  job_landed_at?:      string | null;
  job_landed_role?:    string | null;
  job_landed_company?: string | null;
}

export interface Usage {
  ai_calls: number;
  call_count?: number;
  /** null means unlimited (pro/elite) */
  limit?: number | null;
  remaining?: number | null;
  /** ISO timestamp of when the monthly cap resets; null for unlimited plans */
  resets_at?: string | null;
  /** P1-A: sessions completed this IST month (free tier only) */
  session_count?: number;
  /** P1-A: monthly session cap; null = no cap (paid plans) */
  session_limit?: number | null;
}

export interface UserStats {
  streak: number;
  sessions: number;
  best_score: number;
  last_session?: string;
  avg_job_ready_score?: number;
}

export interface Session {
  id: string;
  user_id: string;
  profession: string;
  mode: SessionMode;
  difficulty: Difficulty;
  interview_type: InterviewType;
  personality: Persona;
  score: number;
  exchanges: number;
  duration_secs: number;
  hindi_mode: boolean;
  job_ready_score?: number;
  clarity_score?: number;
  structure_score?: number;
  relevance_score?: number;
  grammar_score?: number;
  // Interviewer's Notes — 2-3 sentence narrative summary generated by a
  // background job shortly after the session is saved. Null until that
  // job completes (or forever, if it failed — non-fatal by design), so
  // callers must handle the missing case rather than assuming it's set.
  interviewer_notes?: string | null;
  created_at: string;
}

export interface Feedback {
  id: string;
  session_id: string;
  question: string;
  answer?: string;
  score: number;
  tips?: string;
  corrections?: ErrorCorrection[];
  interview_feedback?: string;
  english_errors?: ErrorCorrection[];
  corrected_answer?: string | null;
  structure?: StructureFeedback;
  model_answer?: ModelAnswer;
  tip?: string;
}

export interface ErrorCorrection {
  mistake?: string;
  wrong?: string;
  correction?: string;
  correct?: string;
  explanation?: string;
  rule?: string;
}

export interface StructureFeedback {
  type: string;
  score: number;
  present_parts: string[];
  missing_parts: string[];
  fix: string;
}

export interface ModelAnswer {
  good: string;
  great: string;
}

export interface WeakArea {
  topic: string;
  avg_score: number;
  drill_prompt?: string;
}

export interface JobReadiness {
  score: number;
  label: string;
  color: string;
  message: string;
}

export interface ReferralData {
  code: string;
  uses: number;
  rewarded: number;
  bonus_calls: number;
  // backend computes ready-to-use share copy (accurate to the
  // actual reward mechanic — bonus calls only land after the referred
  // friend completes their first session, not on registration) so the
  // frontend doesn't need to duplicate that logic in a hardcoded string.
  share_context?: {
    whatsapp_url:     string;
    copy_text:        string;
    invite_headline:  string;
    reward_line:      string;
  };
}

// API response wrapper

export interface ApiOk<T> {
  ok: true;
  data: T;
}

export interface ApiErr {
  ok: false;
  status: number;
  // request_id correlates this error with backend logs/Sentry — see
  // lib/api.ts's extractErrorMessage / withErrorRef, which surface it to
  // the user as a support reference ("Error ref: abc123").
  error: { code: string; message: string; request_id?: string; details?: Record<string, unknown> } | string;
}

export type ApiResult<T> = ApiOk<T> | ApiErr;

// Interview session state (live, not persisted)

export interface LiveSessionConfig {
  profession: string;
  mode: SessionMode;
  interviewType: InterviewType;
  difficulty: Difficulty;
  totalQ: number;
  timerSecs: number;
  persona: Persona;
  maxExchanges: number;
  lang: 'en' | 'hi' | 'hinglish';
  /** Raw job description text pasted by the user on the setup screen.
   *  When set, session/page.tsx calls /api/interview/jd-questions to get
   *  tailored questions instead of the generic AI prompt. Optional so
   *  existing sessions without a JD are unaffected. */
  jdText?: string;
  /**
   * Controls whether the Simli avatar is rendered.
   *   'full'       — avatar + voice (default when the feature is available)
   *   'voice-only' — audio-only fallback; no avatar iframe is mounted
   * Omitting the field is equivalent to 'full'. The session page reads
   * this and either initialises SimliClient or skips it entirely.
   */
  avatarMode?: 'full' | 'voice-only';
}

// Within-session memory — built up as answers come in, injected into
// subsequent AI calls so Aria avoids repeating weak patterns and raises
// difficulty after consistent strong answers.
export interface SessionMemory {
  weakTopics:     string[];   // question topics where score < 5
  strongTopics:   string[];   // question topics where score >= 8
  hintsUsed:      number;     // total hints requested this session
  correctionCounts: number[]; // grammar/correction count per answer (proxy for filler trend)
  answerLengths:  number[];   // word count per answer (proxy for pace trend)
  consecutiveStrong: number;  // how many answers in a row scored >= 7
}

export interface LiveSessionState {
  questions: string[];
  currentQ: number;
  allFeedbacks: Feedback[];
  allErrors: ErrorCorrection[];
  chatHistory: { role: 'user' | 'assistant'; content: string }[];
  chatExchanges: number;
  chatErrors: ErrorCorrection[];
  sessionStartTime: number | null;
  timerRemaining: number;
  clientSessionId: string | null;
  lastSessionId: string | null;
  voiceReplies: boolean;
  sessionMemory: SessionMemory;
}

// Onboarding

export interface OnboardingState {
  done: boolean;
  profession?: string;
  goal?: string;
}

// Upgrade modal

export type UpgradeTrigger =
  | 'limit_hit'
  | 'feature_lock'
  | 'voice_fallback'
  | 'strip'
  | 'nudge'
  | 'session_end'
  | null;
